spring:
  application:
    name: auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/api_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1 FROM DUAL
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: auth
info:
  app.name: auth
  company.name: www.wanghuiwen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$