server:
  port: 8084

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true
zuul:
  prefix: /api
  ignored-services: consumer
  routes:
    mydept.serviceId: consumer
    mydept.path: /cu/**

info:
  app.name: gateway
  company.name: www.wanghuiwen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$