server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: gateway
    prefer-ip-address: true

info:
  app.name: gateway
  company.name: www.wanghuiwen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$