spring:
  application:
    name: auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1 FROM DUAL
  data:
    elasticsearch:
      repositories:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
feign:
  hystrix:
    enabled: true

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: auth

security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin123456
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
      jwt:
        key-uri: http://localhost:8081/oauth/token_key
    authorization:
      check-token-access: http://localhost:8081/oauth/check_token
upload:
  img:
    file-path: /home/wanghuiwen/photo/
    host: http://localhost:8080/
    prefix: image/
auth:
  whitelist: /article/list/index
info:
  app.name: auth
  company.name: www.wanghuiwen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$