spring:
  application:
    name: consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/api_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1 FROM DUAL
server:
  port: 8082
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: consumer

security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin123456
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
      jwt:
        key-uri: http://localhost:8081/oauth/token_key
    authorization:
        check-token-access: http://localhost:8081/oauth/check_token

info:
  app.name: consumer
  company.name: www.wanghuiwen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$